export const CharacterIds = {
  Adler: "adler",
  Aurelia: "aurelia",
  Baicang: "baicang",
  Chaos: "chaos",
  Chiz: "chiz",
  Daffodill: "daffodill",
  Edgar: "edgar",
  EsperZero: "esper-zero",
  Fadia: "fadia",
  Haniel: "haniel",
  Hathor: "hathor",
  Hotori: "hotori",
  Jiuyuan: "jiuyuan",
  Lacrimosa: "lacrimosa",
  Mint: "mint",
  Nanally: "nanally",
  Sakiri: "sakiri",
  Skia: "skia",
} as const;
