export const Stats = {
  ANIMA_DMG_BONUS: "Бонус к урону анимы",
  ATK: "Атака",
  ATK_PERCENTAGE: "Атака %",
  BREAK_INTENSITY: "Интенсивность разрушения",
  CHARGE_EFFICIENCY: "Скорость зарядки",
  COSMOS_DMG_BONUS: "Бонус к урону космоса",
  CRIT_DMG: "Крит. урон",
  CRIT_RATE: "Шанс крит. удара",
  CYCLE_INTENSITY: "Интенсивность цикла",
  DEF: "Защита",
  DEF_PERCENTAGE: "Защита %",
  DMG: "Урон",
  DMG_PERCENTAGE: "Урон %",
  HP: "ОЗ",
  HP_PERCENTAGE: "ОЗ%",
  INCANTATION_DMG_BONUS: "Бонус к урону чар",
  LAKSHANA_DMG_BONUS: "Бонус к урону лакшаны",
} as const;
