export const Stats = {
  ANIMA_DMG_BONUS: "Бонус к урону анимы",
  ATK: "Атака",
  ATK_BONUS: "Множитель атака",
  BREAK_INTENSITY: "Интенсивность разрушения",
  CHAOS_DMG_BONUS: "Бонус к урону хаоса",
  CHARGE_EFFICIENCY: "Скорость зарядки",
  COSMOS_DMG_BONUS: "Бонус к урону космоса",
  CRIT_DMG: "Крит. урон",
  CRIT_RATE: "Шанс крит. удара",
  CYCLE_INTENSITY: "Эссентия",
  DEF: "Защита",
  DEF_BONUS: "Множитель защита",
  HEALING_BONUS: "Бонус к лечению",
  HP: "ОЗ",
  HP_BONUS: "Множитель ОЗ",
  INCANTATION_DMG_BONUS: "Бонус к урону чар",
  LAKSHANA_DMG_BONUS: "Бонус к урону лакшаны",
  MENTAL_DMG_BONUS: "Бонус к урону когнитивности",
  PSYCHE_DMG_BONUS: "Бонус к урону психики",
  UNIVERSAL_DMG_BONUS: "Бонус к урону",
} as const;
